### PR TITLE
GitHub-Contained SBS Testing

### PR DESCRIPTION
**Pull request by roshankern**
This PR performs the following:
- Create new `1_sbs/` folder in `example_analysis` that will be used as space for refactored code from `sbs_1`.
- Add `sbs_dev_requirements.yaml` file that contains full details about Python environment (name, version, packages). Although we might move to a settle on a different environment setup later, this requirements file is a step towards a reproducible but flexible environment that works on multiple machines/setups. For now this file only includes the packages I had to manually install with Conda when using the repo from scratch on a machine off the WI network.
- Add example data from Cheeseman Lab screens to `1_sbs/` input folders. This is a step towards a fully GitHub-contained repo that those outside of the Cheeseman lab can easily use. The output folders have been added to the `.gitignore` file for now as they are too large to commit without GitHub LFS. There are multiple options we can explore for including those files (GH LFS, reducing example file usage, other online storage) but for now we leave this for another PR.
- Refactor test notebooks for SBS so they are more clear, concise, and have input/output paths coded with variables instead of hardcoded. We will continue to look for ways to integrate tile-based/well-based code as efficiently as possible.

Please review when you get a chance @mat10d!

### CODE REVIEW

**Comment by mat10d** [comment]
Looks good on my end. I think some thought needs to be put into what env we are using for these approaches. I think fine for now to get a new env that we are using, but longer term, we probably want to have one unified one. You are using the venv for the snakemake?

**Comment by roshankern** [comment]
> Looks good on my end. I think some thought needs to be put into what env we are using for these approaches. I think fine for now to get a new env that we are using, but longer term, we probably want to have one unified one.

I definitely agree.

> You are using the venv for the snakemake?

I have not run the full snakemake pipeline yet on example data (next step for this new GH contained example) but was using the venv to start running the pipeline with all screen data (I stopped it at DAGs step).

**Comment by mat10d** [comment]
Ok, what I would do is this then. In  `OpticalPooledScreens/example_analysis/1_sbs`, have a subfolder of files that are the input files `input_sbs_tif`. Then modify the notebooks to read out into the `tif` subfolder for all the expected outputs.

You should be able to run the snakemake on that folder in example_analysis. You just have to modify the well number to only be A1, and the tile to only be 50. 

I would merge once you have changed the input and output paths in the notebook. Then you can work on the snakemake and making sure it works there?

You should be able to run the notebook using the original venv, maybe that will help without complicating too many things. I don't imagine anyone would run just the notebook and not the snakemake, so not sure it is necessary to have a separate env for the notebook, long term

**Comment by roshankern** [comment]
> Ok, what I would do is this then. In OpticalPooledScreens/example_analysis/1_sbs, have a subfolder of files that are the input files input_sbs_tif. Then modify the notebooks to read out into the tif subfolder for all the expected outputs.
You should be able to run the snakemake on that folder in example_analysis. You just have to modify the well number to only be A1, and the tile to only be 50.
I would merge once you have changed the input and output paths in the notebook. Then you can work on the snakemake and making sure it works there?

For an example, I think it is more clear for a user to see the inputs/outputs split into tool use case. I.e., if the user wants to see how to do a tile-based analysis they go into that folder to see the inputs/outputs for this use case. Putting inputs/outputs in same folders for tile and well based might be confusing for someone new to the tool/repo.  Am I misinterpreting how a new user would use this repo?

> You should be able to run the notebook using the original venv, maybe that will help without complicating too many things. I don't imagine anyone would run just the notebook and not the snakemake, so not sure it is necessary to have a separate env for the notebook, long term

I explain in more depth why I made a completely different environment in #5. TLDR: the original venv was not reproducible on machines outside of the WI HPC network. Although I may have been too hasty to create it in conda and introduce this new env to the repo in this PR...

Would it make more sense to continue our development with the original venv and have the package management discussion later? If so I will stick with the original venv for now, as I agree that we don't want to complicate things.

**Comment by roshankern** [comment]
As discussed during our meeting, we will move to a much simpler version of a GitHub-contained example analysis. The example will only be relevant to tile-based analysis.

We include a new dev environment in this PR that will have packages added to it as we develop to keep the environment as clean as possible.

**Pull request merged**
