### PR TITLE
Move SBS Snake code to separate file

### PR DESCRIPTION
**Pull request by roshankern**
@mat10d this is ready for review!

This PR copies all code relevant to the `example_analysis/sbs_1/tile-based/sbs_1_smk_test.ipynb` notebook to a new `ops/sbs_smk.py` file. Although this migrated code still has lots to improve and fix (ex #2), for this PR we just migrate relevant code to a separate file.

### CODE REVIEW

**Comment by mat10d** [comment]
Looks good, but lacks the snakemake wrapper functions--are you just testing if it works in the notebook first?

**Comment by roshankern** [comment]
> Looks good, but lacks the snakemake wrapper functions--are you just testing if it works in the notebook first?

Nope, I just missed these. Thanks for catching! If this looks good I'll merge after your approval.

**Comment by mat10d** [comment]
Looks good now. Let me know if you are able to test the snakemake as well. You can try it for some small number tile x well combination.

**Comment by roshankern** [comment]
Given our choice (discussed in DMs) to test the snakemake process on files that we upload to this GitHub, I will merge this PR as is and create another PR to upload the example files and use these for the snakemake test. 

This way we can practice avoiding large PRs :)

**Pull request merged**
